name: Build RemoRaids Mod

on:
  push:
    branches:
      - main  # คอมไพล์เมื่อ push ไปที่ branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew  # ✅ แก้ปัญหา permission denied

      - name: Run Gradle Build
        run: ./gradlew build

      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RemoRaids-1.16.5
          path: build/libs/*.jar
